--- # Playbook Example
- name: Install Ngnix on multiple Linux distributions
  hosts: linux-hosts
  become: yes
  gather_facts: yes

  tasks:
    - name: Install EPEL repository (RHEL-based systems)
      package:
        name: epel-release
        state: present
      when: absible_os_family == 'RedHat'

    - name: Install Nginx (Denian/Ubuntu/Kali)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx (RHEL-based systems)
      package:
        name: ngnix
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure Nginx service is running and ebabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Allow HTTP/HTTPS in firewall (UFW - Debiab/Ubuntu/Kali)
      ufw:
        rule: allow
        name: 'Nginx Full'
      when:
        - ansible_os_family == 'Debian'
        - ansible_service_mgr == 'systemd'
    
    - name: Allow HTTP/HTTPS in firewall (Firewalld - RHEL-based)
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
      when: ansible_os_family == 'RedHat'

    - name: Stop Apache if running (Kali Linux specific)
      service:
        name: apache2
        state: stopped
        enabled: no
      when:
        - ansible_distribution == "Kali"
        - ansible_service_mgr == 'systemd'

